version: "3"
services:
  golang:
    container_name: go_container
    build: ./golang
    tty: true
    volumes:
      - ./golang:/usr/src/golang
    environment:
      MYSQL_HOST: mysql_container
    depends_on:
      - mysql
  mysql:
    container_name: mysql_container
    build: ./mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recordings
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      # - ./mysql/db/init:/docker-entrypoint-initdb.d
      - ./mysql/db/data:/var/lib/mysql
