name: CI for fuzz

on: push

jobs:
  setup:
    name: Setup
    strategy:
      matrix:
        go-version: [1.18.x, 1.17.x]
    runs-on: ubuntu-20.04
    steps:
      - name: Init setup
        run: echo "Init setup..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go
        id: cache-golang
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.*') }}
          restore-keys: |
            ${{ runner.os }}-go-
  test-fuzz:
    name: Test fuzz
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'fuzz/go.mod'
      - name: Retrieve cached Go setup
        uses: actions/cache@v3
        id: cache-golang
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.*') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Go test
        working-directory: fuzz
        run: go test
  test-example-greetings:
    name: Test example/greetings
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'example/greetings/go.mod'
      - name: Retrieve cached Go setup
        uses: actions/cache@v3
        id: cache-golang
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.*') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Go test
        working-directory: example/greetings
        run: go test
