name: CI for fuzz

on:
  push:
    paths:
      - 'fuzz/**'

defaults:
  run:
    working-directory: fuzz

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init setup
        run: echo "Init setup..."
